apiVersion: v1
kind: Pod
metadata:
  name: branch1
spec:
  containers:
  - name: maven
    image: maven:3.3.9-jdk-8-alpine
    command:
    - cat
    tty: true
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: ["--dockerfile=/context/Dockerfile",
           "--context=/context",
           "--destination=172.16.33.100:8082/repository/clouddv-docker:1.3"]
    volumeMounts:
      - name: context
        mountPath: /context
      - name:  myregistry-creds
        mountPath: /root/
  restartPolicy: Never
  volumes:
    - name: myregistry-cred
      projected:
        sources:
        - secret:
            name: myregistry-cred
            items:
            - key: .dockerconfigjson
              path: .docker/config.json
    - name: context
      configMap:
        name: kaniko-context